kind: pipeline
type: docker
name: publish

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: hashbang/drone-kaniko
      username: hashbangbot
      password:
        from_secret: DOCKER_RO_PASSWORD
      purge: true
      dry_run: true
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: publish

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: hashbang/drone-kaniko
      auto_tag: true
      username: hashbangbot
      password:
        from_secret: DOCKER_PASSWORD

trigger:
  event:
    - tag
